spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          username: root
          password: 123456
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://localhost:3306/tacomall?serverTimezone=Asia/Shanghai
  redis:
    host: 127.0.0.1
    port: 7010
    password: 123456
jobs:
  admin-address: http://127.0.0.1:5000
  app-name: job-executor
  app-port: 9999