server:
  port: 4002

spring:
  profiles:
    active: @environment@

logging:
  level:
    com.baomidou: debug

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
  type-aliases-package: store.tacomall.mapper
  mapper-locations: classpath:/mapper/*Mapper.xml